### ISSUE TITLE
Doesn't work with Warp terminal

### ISSUE THREAD

**Issue by ilmari-aalto** [dbt-labs/dbt-completion.bash#17]
Hi,

dbt completion doesn't seem to work with the new Warp terminal. This might have to do with the fact that Warp doesn't use `<tab>` for auto-completion but the right arrow key instead.

dbt completion works with iTerm on Mac. (It's sourced as part of my `~/.bash_profile` and so on.) However, nothing happens when I'm trying to use `<tab>` or the right arrow key to auto-complete a dbt node name.

**Comment by b-per** [comment]
Nothing we can do in this repo though. I am on the same boat.
